---
title: "Interpretability_Graphs"
author: "Christophe Regouby"
date: "25/06/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Library
library(DiagrammeR)
library(networkD3)
library(tidyverse)
```

## Show me your model Decision Tree

```{r diagrammeR decision tree }
grViz("
digraph high_level_showme {
  graph [overlap = true,  fontsize = 19, layout = dot, rankdir=LR, compound = true, nodesep = .5, ranksep = .25,
         color=crimpson]
  node [shape = none, fontname = impact, style=filled, fillcolor = dodgerblue3, fontcolor=white, alpha=0.5 ]
  'Montre-moi ton mod舶e';

  subgraph clusterds {
    node [shape = none, fontname = impact, style=filled, fillcolor = deepskyblue1, fontcolor=black, alpha=0.5  ]
    'Je veux comprendre le\nmod舶e globalement' 'Le mod舶e est-il bon?' 'Comment fonctionne-t-il?'} ;
    'Montre-moi ton mod舶e' -> 'Je veux comprendre le\nmod舶e globalement' [lhead = clusterds];
    'Je veux comprendre le\nmod舶e globalement' -> 'Le mod舶e est-il bon?' ;
    'Je veux comprendre le\nmod舶e globalement' -> 'Comment fonctionne-t-il?';

  subgraph clusterconsumer {
    node [shape = none, fontname = impact, style=filled, fillcolor = deepskyblue1, fontcolor=black, alpha=0.5  ]
    'Je veux comprendre\nune prediction' 'Et si je change ceci ?' 'Comment est-ce que les variables\naffectent la prediction ?' };
    'Montre-moi ton mod舶e' -> 'Je veux comprendre\nune prediction'-> 'Et si je change ceci ?' [lhead = clusterconsumer];
    'Je veux comprendre\nune prediction'-> 'Comment est-ce que les variables\naffectent la prediction ?';
}
")
```


```{r diagrammeR decision tree 2}
grViz("
digraph full_stack_showme {
  graph [overlap = true, fontsize = 10, fontname = Impact, layout = dot, rankdir=LR, compound = true, nodesep = .05, ranksep = .25,
         color=crimpson]
  node [shape = none, fontname = impact, style=filled, fillcolor = dodgerblue3, fontcolor=white, alpha=0.5 ]
  'Montre-moi ton mod舶e';

  subgraph clusterds {
    node [shape = none, fontname = impact, style=filled, fillcolor = deepskyblue1, fontcolor=black, alpha=0.5  ]
    'Je veux comprendre le\nmod舶e globalement' 'Le mod舶e est-il bon?' 'Je veux comparer les mod舶es entre eux' 'Comment fonctionne-t-il?'
    'Je veux voir la prediction qualitativement' 'Je veux auditer les r乶idus' 'Toutes variables confondues' 'Pour une variable cat服orielle' 'Pour une variable continue'} ;
    'Montre-moi ton mod舶e' -> 'Je veux comprendre le\nmod舶e globalement' [lhead = clusterds];
  'Je veux comprendre le\nmod舶e globalement' -> 'Le mod舶e est-il bon?' -> 'Je veux comparer les mod舶es entre eux';
  'Le mod舶e est-il bon?' -> 'Je veux voir la prediction qualitativement'; 'Le mod舶e est-il bon?' -> 'Je veux auditer les r乶idus'
  'Je veux comprendre le\nmod舶e globalement' -> 'Comment fonctionne-t-il?'-> 'Toutes variables confondues'; 'Comment fonctionne-t-il?' -> 'Pour une variable cat服orielle' ; 'Comment fonctionne-t-il?' -> 'Pour une variable continue'

  subgraph clusterconsumer {
    node [shape = none, fontname = impact, style=filled, fillcolor = deepskyblue1, fontcolor=black, alpha=0.5  ]
    'Je veux comprendre\nune prediction' 'Et si je change ceci ?' 'Comment est-ce que les variables\naffectent la pr卜iction ?' 'Peut-on d匐omposer\nla pr卜iction ?'
    'Quelle est l알mportance\nde chaque variable ici ?'} ;
  'Montre-moi ton mod舶e' -> 'Je veux comprendre\nune prediction'-> 'Et si je change ceci ?' [lhead = clusterconsumer];
  'Je veux comprendre\nune prediction'-> 'Comment est-ce que les variables\naffectent la pr卜iction ?' -> 'Peut-on d匐omposer\nla pr卜iction ?';
  'Comment est-ce que les variables\naffectent la pr卜iction ?' -> 'Quelle est l알mportance\nde chaque variable ici ?'
}
")
```


```{r diagrammeR decision tree 3}
grViz("
digraph and_the_plots_for_ds {
  graph [overlap = true, fontsize = 10, layout = twopi, nodesep = .3, ranksep = 1.3]
  node [shape = box, penwidth=2, fontname = impact, width=5, style=filled, fillcolor = dodgerblue3, fontcolor=white, alpha=0.5 ]
  'Montre-moi ton mod舶e';

  node [shape = none, width=auto, fillcolor = deepskyblue3, fontcolor=black ]
  'Montre-moi ton mod舶e' -> 'Je veux comprendre le\nmod舶e globalement' -> {'Le mod舶e est-il bon?' 'Comment fonctionne-t-il?'}
  'Montre-moi ton mod舶e' -> {'Je veux comprendre\nune prediction' 'Comment est-ce que les variables\naffectent la pr卜iction ?'}
  
  node [fillcolor = deepskyblue1, fontcolor=black ]
  'Le mod舶e est-il bon?' -> {'Je veux voir la prediction qualitativement' 'Je veux auditer les r乶idus'}
  'Je veux voir la prediction qualitativement'-> 'Je veux comparer les mod舶es entre eux';
  'Comment fonctionne-t-il?'-> {'Toutes variables confondues' 'Pour une variable cat服orielle' 'Pour une variable continue'}
  'Je veux comprendre\nune prediction'-> 'Et si je change ceci ?'
  'Comment est-ce que les variables\naffectent la pr卜iction ?' -> {'Peut-on d匐omposer la pr卜iction ?' 'Quelle est l알mportance\nde chaque variable ici ?'}

  node [shape = none, fillcolor = grey90, fontcolor=black ]
  'Je veux auditer les r乶idus' -> 'Residual Diagnostic Plot';
  'Je veux comparer les mod舶es entre eux' -> 'Model Performance Plot';
  'Je veux voir la prediction qualitativement' -> 'Quantile-Quantile plot';
  'Toutes variables confondues' -> 'Variable Importance';
  'Pour une variable cat服orielle' -> 'Merging Path Plot';
  'Pour une variable continue' -> 'Partial Dependancy Plot';
  'Et si je change ceci ?' -> 'Ceteris Paribus Plot';
  'Peut-on d匐omposer la pr卜iction ?' -> 'BreakDown'; 'Peut-on d匐omposer la pr卜iction ?' -> 'Shapley Plot';
  'Quelle est l알mportance\nde chaque variable ici ?' -> 'Local Variable Importance'
}
")
```

